# Generated by Django 4.2 on 2023-04-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandhistory',
            old_name='year_created',
            new_name='year',
        ),
    ]
