# Generated by Django 4.2 on 2023-04-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_year_created_bandhistory_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandmember',
            name='year_joined',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bandmember',
            name='instrument',
            field=models.CharField(max_length=50),
        ),
    ]
