# Generated by Django 4.2 on 2023-04-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bandmember_year_joined_alter_bandmember_instrument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandhistory',
            options={'verbose_name_plural': 'Band History'},
        ),
    ]
