# Generated by Django 4.2 on 2023-04-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_bandhistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandmember',
            options={'verbose_name_plural': 'Band Members'},
        ),
        migrations.AddField(
            model_name='bandmember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='band_members'),
        ),
        migrations.AlterField(
            model_name='bandmember',
            name='instrument',
            field=models.CharField(max_length=100),
        ),
    ]
