# Generated by Django 4.2 on 2023-04-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_bandmember_options_bandmember_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandmember',
            options={},
        ),
        migrations.AlterField(
            model_name='bandmember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bandmember',
            name='instrument',
            field=models.CharField(max_length=50),
        ),
    ]
