# Generated by Django 4.2 on 2023-04-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_bandmember_options_alter_bandmember_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandmember',
            name='image',
        ),
    ]
